version: '3'
services:
  quiz-game:
    build: .
    container_name: quiz-game
    ports:
      - "3002:3000"
    volumes:
      - ./public:/app/public
      - ./questions.csv:/app/questions.csv
      - ./server.js:/app/server.js
      - ./questionBank.js:/app/questionBank.js
    environment:
      - NODE_ENV=development
    restart: unless-stopped
